  {
   "jobs" : {
      "test" : {
         "env" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/test"
         },
         "runs-on" : "ubuntu-latest",
         "steps" : [
            {
               "uses" : "actions/checkout@v2",
               "with" : {
                  "ssh-key" : "${{ secrets.GH_GIT_KEY }}"
               }
            },
            {
               "run" : "mkdir -p $CIRCLE_ARTIFACTS"
            },
            {
               "run" : "docker build -t quay\u005C.io\u005C/wakaba\u005C/samba ."
            },
            {
               "env" : {
                  "DOCKER_PASS" : "${{ secrets.DOCKER_PASS }}",
                  "DOCKER_USER" : "${{ secrets.DOCKER_USER }}"
               },
               "if" : "${{ github.ref == 'refs/heads/master' }}",
               "run" : "docker login -u $DOCKER_USER -p $DOCKER_PASS quay\u005C.io"
            },
            {
               "if" : "${{ github.ref == 'refs/heads/master' }}",
               "run" : "docker push quay\u005C.io\u005C/wakaba\u005C/samba"
            },
            {
               "if" : "${{ always () }}",
               "uses" : "actions/upload-artifact@v4",
               "with" : {
                  "path" : "/tmp/circle-artifacts/test"
               }
            }
         ]
      }
   },
   "name" : "test",
   "on" : {
      "push" : {
      }
   }
}
